languages:
    JavaScript: true
exclude_paths: 
    - bin/*
    - db/*
    - include/*
    - logs/*
    - rel/*
    - src/*
    - static/fonts/*
    - static/ico/*
    - static/img/*
    - static/less/*
    - templats/*
    - translations/*
